networks:
  proxylampy:
    external: true
services:
 www:
    image: node:22.12.0
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev --host=0.0.0.0"
    volumes:
      - ${PWD}/apps:/app:delegated
    networks:
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nuxtjs.rule=Host(`nuxtjs.traefik.me`)"
        - "traefik.http.routers.nuxtjs-tls.tls.domains[0].main=nuxtjs.traefik.me"
        - "traefik.http.routers.nuxtjs.tls=true"
        - "traefik.http.services.nuxtjs.loadbalancer.server.port=3000"
